// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: magos/v1/agent/agent.proto

package agent

import (
	types "github.com/Hahn814/magos/proto/magos/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_magos_v1_agent_agent_proto protoreflect.FileDescriptor

const file_magos_v1_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x1amagos/v1/agent/agent.proto\x12\x05agent\x1a\x1amagos/v1/types/types.proto2\x86\x01\n" +
	"\x05Agent\x124\n" +
	"\x05Hello\x12\x13.types.HelloRequest\x1a\x14.types.HelloResponse\"\x00\x12G\n" +
	"\bDescribe\x12\x1b.types.DescribeAgentRequest\x1a\x1c.types.DescribeAgentResponse\"\x00B/Z-github.com/Hahn814/magos/proto/magos/v1/agentb\x06proto3"

var file_magos_v1_agent_agent_proto_goTypes = []any{
	(*types.HelloRequest)(nil),          // 0: types.HelloRequest
	(*types.DescribeAgentRequest)(nil),  // 1: types.DescribeAgentRequest
	(*types.HelloResponse)(nil),         // 2: types.HelloResponse
	(*types.DescribeAgentResponse)(nil), // 3: types.DescribeAgentResponse
}
var file_magos_v1_agent_agent_proto_depIdxs = []int32{
	0, // 0: agent.Agent.Hello:input_type -> types.HelloRequest
	1, // 1: agent.Agent.Describe:input_type -> types.DescribeAgentRequest
	2, // 2: agent.Agent.Hello:output_type -> types.HelloResponse
	3, // 3: agent.Agent.Describe:output_type -> types.DescribeAgentResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_magos_v1_agent_agent_proto_init() }
func file_magos_v1_agent_agent_proto_init() {
	if File_magos_v1_agent_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_magos_v1_agent_agent_proto_rawDesc), len(file_magos_v1_agent_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_magos_v1_agent_agent_proto_goTypes,
		DependencyIndexes: file_magos_v1_agent_agent_proto_depIdxs,
	}.Build()
	File_magos_v1_agent_agent_proto = out.File
	file_magos_v1_agent_agent_proto_goTypes = nil
	file_magos_v1_agent_agent_proto_depIdxs = nil
}
