// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: magos/v1/types/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_magos_v1_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magos_v1_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_magos_v1_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_magos_v1_types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magos_v1_types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_magos_v1_types_types_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterAgentServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentServerRequest) Reset() {
	*x = RegisterAgentServerRequest{}
	mi := &file_magos_v1_types_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentServerRequest) ProtoMessage() {}

func (x *RegisterAgentServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magos_v1_types_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentServerRequest) Descriptor() ([]byte, []int) {
	return file_magos_v1_types_types_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgentServerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterAgentServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentServerResponse) Reset() {
	*x = RegisterAgentServerResponse{}
	mi := &file_magos_v1_types_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentServerResponse) ProtoMessage() {}

func (x *RegisterAgentServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magos_v1_types_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentServerResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentServerResponse) Descriptor() ([]byte, []int) {
	return file_magos_v1_types_types_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAgentServerResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_magos_v1_types_types_proto protoreflect.FileDescriptor

const file_magos_v1_types_types_proto_rawDesc = "" +
	"\n" +
	"\x1amagos/v1/types/types.proto\x12\x05types\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"#\n" +
	"\rHelloResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"6\n" +
	"\x1aRegisterAgentServerRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"7\n" +
	"\x1bRegisterAgentServerResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddressB/Z-github.com/Hahn814/magos/proto/magos/v1/typesb\x06proto3"

var (
	file_magos_v1_types_types_proto_rawDescOnce sync.Once
	file_magos_v1_types_types_proto_rawDescData []byte
)

func file_magos_v1_types_types_proto_rawDescGZIP() []byte {
	file_magos_v1_types_types_proto_rawDescOnce.Do(func() {
		file_magos_v1_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_magos_v1_types_types_proto_rawDesc), len(file_magos_v1_types_types_proto_rawDesc)))
	})
	return file_magos_v1_types_types_proto_rawDescData
}

var file_magos_v1_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_magos_v1_types_types_proto_goTypes = []any{
	(*HelloRequest)(nil),                // 0: types.HelloRequest
	(*HelloResponse)(nil),               // 1: types.HelloResponse
	(*RegisterAgentServerRequest)(nil),  // 2: types.RegisterAgentServerRequest
	(*RegisterAgentServerResponse)(nil), // 3: types.RegisterAgentServerResponse
}
var file_magos_v1_types_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_magos_v1_types_types_proto_init() }
func file_magos_v1_types_types_proto_init() {
	if File_magos_v1_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_magos_v1_types_types_proto_rawDesc), len(file_magos_v1_types_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_magos_v1_types_types_proto_goTypes,
		DependencyIndexes: file_magos_v1_types_types_proto_depIdxs,
		MessageInfos:      file_magos_v1_types_types_proto_msgTypes,
	}.Build()
	File_magos_v1_types_types_proto = out.File
	file_magos_v1_types_types_proto_goTypes = nil
	file_magos_v1_types_types_proto_depIdxs = nil
}
