// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/magos/v1/daemon.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_magos_v1_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_magos_v1_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_magos_v1_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_proto_magos_v1_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_magos_v1_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_magos_v1_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_magos_v1_daemon_proto protoreflect.FileDescriptor

const file_proto_magos_v1_daemon_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/magos/v1/daemon.proto\x12\bmagos.v1\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"#\n" +
	"\rHelloResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2C\n" +
	"\x05Agent\x12:\n" +
	"\x05Hello\x12\x16.magos.v1.HelloRequest\x1a\x17.magos.v1.HelloResponse\"\x00B\tZ\acmd/apib\x06proto3"

var (
	file_proto_magos_v1_daemon_proto_rawDescOnce sync.Once
	file_proto_magos_v1_daemon_proto_rawDescData []byte
)

func file_proto_magos_v1_daemon_proto_rawDescGZIP() []byte {
	file_proto_magos_v1_daemon_proto_rawDescOnce.Do(func() {
		file_proto_magos_v1_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_magos_v1_daemon_proto_rawDesc), len(file_proto_magos_v1_daemon_proto_rawDesc)))
	})
	return file_proto_magos_v1_daemon_proto_rawDescData
}

var file_proto_magos_v1_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_magos_v1_daemon_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: magos.v1.HelloRequest
	(*HelloResponse)(nil), // 1: magos.v1.HelloResponse
}
var file_proto_magos_v1_daemon_proto_depIdxs = []int32{
	0, // 0: magos.v1.Agent.Hello:input_type -> magos.v1.HelloRequest
	1, // 1: magos.v1.Agent.Hello:output_type -> magos.v1.HelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_magos_v1_daemon_proto_init() }
func file_proto_magos_v1_daemon_proto_init() {
	if File_proto_magos_v1_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_magos_v1_daemon_proto_rawDesc), len(file_proto_magos_v1_daemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_magos_v1_daemon_proto_goTypes,
		DependencyIndexes: file_proto_magos_v1_daemon_proto_depIdxs,
		MessageInfos:      file_proto_magos_v1_daemon_proto_msgTypes,
	}.Build()
	File_proto_magos_v1_daemon_proto = out.File
	file_proto_magos_v1_daemon_proto_goTypes = nil
	file_proto_magos_v1_daemon_proto_depIdxs = nil
}
