// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/legion/v1/legion.proto

package legion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Legion_Hello_FullMethodName = "/legion.v1.Legion/Hello"
)

// LegionClient is the client API for Legion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LegionClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type legionClient struct {
	cc grpc.ClientConnInterface
}

func NewLegionClient(cc grpc.ClientConnInterface) LegionClient {
	return &legionClient{cc}
}

func (c *legionClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, Legion_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LegionServer is the server API for Legion service.
// All implementations must embed UnimplementedLegionServer
// for forward compatibility.
type LegionServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedLegionServer()
}

// UnimplementedLegionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLegionServer struct{}

func (UnimplementedLegionServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedLegionServer) mustEmbedUnimplementedLegionServer() {}
func (UnimplementedLegionServer) testEmbeddedByValue()                {}

// UnsafeLegionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LegionServer will
// result in compilation errors.
type UnsafeLegionServer interface {
	mustEmbedUnimplementedLegionServer()
}

func RegisterLegionServer(s grpc.ServiceRegistrar, srv LegionServer) {
	// If the following call pancis, it indicates UnimplementedLegionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Legion_ServiceDesc, srv)
}

func _Legion_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LegionServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Legion_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LegionServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Legion_ServiceDesc is the grpc.ServiceDesc for Legion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Legion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "legion.v1.Legion",
	HandlerType: (*LegionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Legion_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/legion/v1/legion.proto",
}
